# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutQt(object):
    def setupUi(self, AboutQt):
        AboutQt.setObjectName("AboutQt")
        AboutQt.resize(601, 553)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rc/images/lined_up_32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutQt.setWindowIcon(icon)
        AboutQt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(AboutQt)
        self.gridLayout.setContentsMargins(0, -1, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(AboutQt)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/rc/images/about_qt.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.frameAboutQt = QtWidgets.QFrame(AboutQt)
        self.frameAboutQt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.frameAboutQt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAboutQt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAboutQt.setObjectName("frameAboutQt")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameAboutQt)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(497, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonAbout = QtWidgets.QPushButton(self.frameAboutQt)
        self.pushButtonAbout.setObjectName("pushButtonAbout")
        self.horizontalLayout.addWidget(self.pushButtonAbout)
        self.gridLayout.addWidget(self.frameAboutQt, 1, 0, 1, 1)

        self.retranslateUi(AboutQt)
        QtCore.QMetaObject.connectSlotsByName(AboutQt)

    def retranslateUi(self, AboutQt):
        _translate = QtCore.QCoreApplication.translate
        AboutQt.setWindowTitle(_translate("AboutQt", "关于Qt"))
        self.pushButtonAbout.setText(_translate("AboutQt", "OK"))
