# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Base(object):
    def setupUi(self, Base):
        Base.setObjectName("Base")
        Base.resize(336, 194)
        self.gridLayout = QtWidgets.QGridLayout(Base)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Base)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(Base)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 3)
        self.label = QtWidgets.QLabel(Base)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Base)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.pushButton_accepted = QtWidgets.QPushButton(Base)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_accepted.sizePolicy().hasHeightForWidth())
        self.pushButton_accepted.setSizePolicy(sizePolicy)
        self.pushButton_accepted.setObjectName("pushButton_accepted")
        self.gridLayout.addWidget(self.pushButton_accepted, 2, 2, 2, 1)
        self.label_2 = QtWidgets.QLabel(Base)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Base)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 3, 1, 1, 1)

        self.retranslateUi(Base)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Base)

    def retranslateUi(self, Base):
        _translate = QtCore.QCoreApplication.translate
        Base.setWindowTitle(_translate("Base", "Form"))
        self.label_3.setText(_translate("Base", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">代码与延迟</span></p></body></html>"))
        self.label_4.setText(_translate("Base", "代码必须是带交易所编号的完整代码，获取延迟表示\n"
"两次数据之间的间隔"))
        self.label.setText(_translate("Base", "完整代码"))
        self.lineEdit.setText(_translate("Base", "SZ002594"))
        self.lineEdit.setPlaceholderText(_translate("Base", "如：SZ002594"))
        self.pushButton_accepted.setText(_translate("Base", "确定"))
        self.label_2.setText(_translate("Base", "获取延迟"))
        self.comboBox.setItemText(0, _translate("Base", "2秒"))
        self.comboBox.setItemText(1, _translate("Base", "3秒"))
        self.comboBox.setItemText(2, _translate("Base", "5秒"))
        self.comboBox.setItemText(3, _translate("Base", "10秒"))
