# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Base(object):
    def setupUi(self, Base):
        Base.setObjectName("Base")
        Base.resize(336, 194)
        self.gridLayout = QtWidgets.QGridLayout(Base)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(Base)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(Base)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(Base)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(Base)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(Base)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Base)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 6, 1, 1, 1)
        self.pushButton_accepted = QtWidgets.QPushButton(Base)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_accepted.sizePolicy().hasHeightForWidth())
        self.pushButton_accepted.setSizePolicy(sizePolicy)
        self.pushButton_accepted.setObjectName("pushButton_accepted")
        self.gridLayout.addWidget(self.pushButton_accepted, 6, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 3)
        self.label_5 = QtWidgets.QLabel(Base)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Base)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 5, 1, 1, 2)

        self.retranslateUi(Base)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Base)

    def retranslateUi(self, Base):
        _translate = QtCore.QCoreApplication.translate
        Base.setWindowTitle(_translate("Base", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Base", "如：SZ002594"))
        self.label_4.setText(_translate("Base", "代码必须是带交易所编号的完整代码，获取延迟表示两次取"))
        self.label_3.setText(_translate("Base", "数据之间的间隔"))
        self.label_2.setText(_translate("Base", "获取延迟"))
        self.label.setText(_translate("Base", "完整代码(1"))
        self.comboBox.setItemText(0, _translate("Base", "2秒"))
        self.comboBox.setItemText(1, _translate("Base", "3秒"))
        self.comboBox.setItemText(2, _translate("Base", "5秒"))
        self.comboBox.setItemText(3, _translate("Base", "10秒"))
        self.pushButton_accepted.setText(_translate("Base", "确定"))
        self.label_5.setText(_translate("Base", "完整代码(2"))
