# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backgroud_color.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BackgroundColor(object):
    def setupUi(self, BackgroundColor):
        BackgroundColor.setObjectName("BackgroundColor")
        BackgroundColor.resize(356, 169)
        self.gridLayout = QtWidgets.QGridLayout(BackgroundColor)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(BackgroundColor)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 75))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_3.addWidget(self.radioButton_2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(BackgroundColor)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 1, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(BackgroundColor)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 2, 1)
        self.pushButton_accepted_2 = QtWidgets.QPushButton(BackgroundColor)
        self.pushButton_accepted_2.setObjectName("pushButton_accepted_2")
        self.gridLayout.addWidget(self.pushButton_accepted_2, 2, 1, 1, 1)

        self.retranslateUi(BackgroundColor)
        QtCore.QMetaObject.connectSlotsByName(BackgroundColor)

    def retranslateUi(self, BackgroundColor):
        _translate = QtCore.QCoreApplication.translate
        BackgroundColor.setWindowTitle(_translate("BackgroundColor", "Form"))
        self.groupBox.setTitle(_translate("BackgroundColor", "Windows 模式"))
        self.radioButton.setText(_translate("BackgroundColor", "浅色"))
        self.radioButton_2.setText(_translate("BackgroundColor", "深色"))
        self.groupBox_3.setTitle(_translate("BackgroundColor", "自定义背景"))
        self.label_8.setText(_translate("BackgroundColor", "调色板"))
        self.pushButton.setText(_translate("BackgroundColor", "PushButton"))
        self.groupBox_2.setTitle(_translate("BackgroundColor", "应用模式"))
        self.radioButton_3.setText(_translate("BackgroundColor", "亮"))
        self.radioButton_4.setText(_translate("BackgroundColor", "暗"))
        self.pushButton_accepted_2.setText(_translate("BackgroundColor", "确定"))
