# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shortcut_key.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShortcutKey(object):
    def setupUi(self, ShortcutKey):
        ShortcutKey.setObjectName("ShortcutKey")
        ShortcutKey.resize(367, 199)
        self.gridLayout = QtWidgets.QGridLayout(ShortcutKey)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(ShortcutKey)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(ShortcutKey)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(ShortcutKey)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(ShortcutKey)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(ShortcutKey)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(ShortcutKey)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 71, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.pushButton_accepted_3 = QtWidgets.QPushButton(ShortcutKey)
        self.pushButton_accepted_3.setObjectName("pushButton_accepted_3")
        self.gridLayout.addWidget(self.pushButton_accepted_3, 4, 1, 1, 1)

        self.retranslateUi(ShortcutKey)
        QtCore.QMetaObject.connectSlotsByName(ShortcutKey)

    def retranslateUi(self, ShortcutKey):
        _translate = QtCore.QCoreApplication.translate
        ShortcutKey.setWindowTitle(_translate("ShortcutKey", "Form"))
        self.label_9.setText(_translate("ShortcutKey", "打开/关闭设置页"))
        self.lineEdit_2.setText(_translate("ShortcutKey", "Alt+S"))
        self.label_10.setText(_translate("ShortcutKey", "显示/隐藏任务栏数据"))
        self.lineEdit_3.setText(_translate("ShortcutKey", "Alt+Space"))
        self.label_11.setText(_translate("ShortcutKey", "老板键"))
        self.lineEdit_4.setText(_translate("ShortcutKey", "Ctrl+Space"))
        self.pushButton_accepted_3.setText(_translate("ShortcutKey", "确定"))
