# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'other.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Other(object):
    def setupUi(self, Other):
        Other.setObjectName("Other")
        Other.resize(423, 266)
        self.gridLayout = QtWidgets.QGridLayout(Other)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Other)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 114))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    background: transparent;\n"
"    color: block;\n"
"    border: none;\n"
"}")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_3.addWidget(self.plainTextEdit)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Other)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_sys = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_sys.setObjectName("checkBox_sys")
        self.horizontalLayout.addWidget(self.checkBox_sys)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Other)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_polling = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_polling.setObjectName("checkBox_polling")
        self.horizontalLayout_2.addWidget(self.checkBox_polling)
        self.checkBox_futures = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_futures.setObjectName("checkBox_futures")
        self.horizontalLayout_2.addWidget(self.checkBox_futures)
        self.checkBox_monitor = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_monitor.setObjectName("checkBox_monitor")
        self.horizontalLayout_2.addWidget(self.checkBox_monitor)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 1)

        self.retranslateUi(Other)
        QtCore.QMetaObject.connectSlotsByName(Other)

    def retranslateUi(self, Other):
        _translate = QtCore.QCoreApplication.translate
        Other.setWindowTitle(_translate("Other", "Form"))
        self.groupBox_3.setTitle(_translate("Other", "提醒"))
        self.plainTextEdit.setPlainText(_translate("Other", "1.若开启了“基础信息、FC 信息”自启动，此时“背景色”将无法再改变。需要你先关闭对应功能的自启动，并重启软件方可修改“背景色”。\n"
"2.需要先开启“基础信息、FC 信息”中的任意一个后，才能开启“监控与提醒”的自启动。"))
        self.groupBox_2.setTitle(_translate("Other", "系统相关"))
        self.checkBox_sys.setText(_translate("Other", "软件开机自启"))
        self.groupBox.setTitle(_translate("Other", "功能自启"))
        self.checkBox_polling.setText(_translate("Other", "基础信息"))
        self.checkBox_futures.setText(_translate("Other", "F C 信息"))
        self.checkBox_monitor.setText(_translate("Other", "监控与提醒"))
