# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'what_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WhatNew(object):
    def setupUi(self, WhatNew):
        WhatNew.setObjectName("WhatNew")
        WhatNew.resize(352, 235)
        self.gridLayout = QtWidgets.QGridLayout(WhatNew)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(WhatNew)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 2, 3)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 2, 3)
        self.label_8 = QtWidgets.QLabel(WhatNew)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(WhatNew)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(WhatNew)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(WhatNew)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(WhatNew)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(WhatNew)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 3)

        self.retranslateUi(WhatNew)
        QtCore.QMetaObject.connectSlotsByName(WhatNew)

    def retranslateUi(self, WhatNew):
        _translate = QtCore.QCoreApplication.translate
        WhatNew.setWindowTitle(_translate("WhatNew", "Form"))
        self.groupBox.setTitle(_translate("WhatNew", "版本信息"))
        self.radioButton_2.setText(_translate("WhatNew", "Gitee 检查"))
        self.label.setText(_translate("WhatNew", "主：<a href=\"https://github.com/YQBaobao/RollerCoaster/releases\">前往 GitHub 查看详细的更新说明</a>"))
        self.label_6.setText(_translate("WhatNew", "更新源："))
        self.radioButton.setText(_translate("WhatNew", "Github检查"))
        self.label_2.setText(_translate("WhatNew", "<html><head/><body><p>备：<a href=\"https://gitee.com/yqbao/roller-coaster/releases\"><span style=\" text-decoration: underline; color:#0000ff;\">前往 Gitee  查看详细的更新说明</span></a></p></body></html>"))
        self.label_8.setText(_translate("WhatNew", "<a href=\"https://www.foxmail.com/\">yqbaowo@foxmail.com</a>"))
        self.label_3.setText(_translate("WhatNew", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">过山车</span>-RollerCoaster</p></body></html>"))
        self.label_5.setText(_translate("WhatNew", "联系我：<a href=\"https://www.cnblogs.com/yqbaowo/\">cnblogs.com</a>"))
        self.label_10.setText(_translate("WhatNew", "邮箱："))
        self.label_4.setText(_translate("WhatNew", "哎嘿：让你时刻体验过山车一样的快感（滑稽）"))
        self.label_7.setText(_translate("WhatNew", "开源协议：<a href=\"https://www.gnu.org/licenses/gpl-3.0.html\">GPL-3.0 license</a>"))
